# Generated by Django 5.2.6 on 2025-09-25 18:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='fahrstundenplaner', max_length=100)),
                ('week_start', models.IntegerField(choices=[(0, 'Sonntag'), (1, 'Montag'), (2, 'Dienstag'), (3, 'Mittwoch'), (4, 'Donnerstag'), (5, 'Freitag'), (6, 'Samstag')], default=1)),
                ('show_week_numbers', models.BooleanField(default=False)),
                ('slot_min_time', models.TimeField(default=datetime.time(6, 0))),
                ('slot_max_time', models.TimeField(default=datetime.time(21, 0))),
                ('slot_duration_min', models.PositiveSmallIntegerField(default=15)),
                ('snap_duration_min', models.PositiveSmallIntegerField(default=15)),
                ('default_new_duration_min', models.PositiveSmallIntegerField(default=45)),
            ],
        ),
    ]
