# Generated by Django 5.2.6 on 2025-09-26 13:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_appsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['start', 'end'], name='core_appoin_start_8effd7_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['instructor', 'start'], name='core_appoin_instruc_645159_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['vehicle', 'start'], name='core_appoin_vehicle_8d493e_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['student', 'start'], name='core_appoin_student_014ad5_idx'),
        ),
    ]
