# Generated by Django 5.2.6 on 2025-10-23 01:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_unavailability'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='unavailability',
            name='core_unavai_instruc_1a3205_idx',
        ),
        migrations.RemoveField(
            model_name='unavailability',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='unavailability',
            name='reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddIndex(
            model_name='unavailability',
            index=models.Index(fields=['start', 'end'], name='core_unavai_start_54f0c9_idx'),
        ),
        migrations.AddIndex(
            model_name='unavailability',
            index=models.Index(fields=['instructor', 'start'], name='core_unavai_instruc_3bb6eb_idx'),
        ),
    ]
