# Generated by Django 5.2.6 on 2025-10-23 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_unavailability_core_unavai_instruc_1a3205_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(unique=True)),
                ('text', models.TextField(blank=True, default='')),
            ],
        ),
    ]
