# Generated by Django 4.2.25 on 2025-12-08 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_weeknote'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeknote',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='week_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='weeknote',
            name='week_start',
            field=models.DateField(),
        ),
        migrations.AddConstraint(
            model_name='weeknote',
            constraint=models.UniqueConstraint(fields=('week_start', 'instructor'), name='uniq_weeknote_per_instructor'),
        ),
    ]
