# Generated by Django 4.2.25 on 2025-12-08 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_weeknote_instructor_alter_weeknote_week_start_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='weeknote',
            index=models.Index(fields=['week_start'], name='core_weekno_week_st_95007c_idx'),
        ),
        migrations.AddIndex(
            model_name='weeknote',
            index=models.Index(fields=['instructor', 'week_start'], name='core_weekno_instruc_ed0b8d_idx'),
        ),
    ]
