"""
Django settings for fahrstundenplaner project.

Generated by 'django-admin startproject' using Django 5.2.6.

Docs:
- Topics: https://docs.djangoproject.com/en/5.2/topics/settings/
- Reference: https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Basisverzeichnis des Projekts (…/fahrstundenplaner)
BASE_DIR = Path(__file__).resolve().parent.parent


# === Quickstart/Dev-Settings (nicht produktionssicher) ===
# In Prod: unbedingt die Deployment-Checklist durchgehen:
# https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# WARNUNG: Secret Key niemals im Repo lassen. In Prod über ENV-Variable laden.
SECRET_KEY = 'django-insecure-urx&25u@^nrfn)uph%5z-o%c_%93-(vy60s3&ro+&b^c#d-abw'

# Dev bequem: DEBUG an. In Prod MUSS DEBUG=False sein.
DEBUG = True

# Hosts whitelisten. In Dev leer ok; in Prod Domain(s)/IP(s) eintragen.
# ALLOWED_HOSTS = ["89.167.61.22", "localhost"]

ALLOWED_HOSTS = ["lichtenberg.fahrschulesafe.com", "www.lichtenberg.fahrschulesafe.com", "89.167.61.22", "localhost", "127.0.0.1"]

CSRF_TRUSTED_ORIGINS = [
    "https://lichtenberg.fahrschulesafe.com",
    "https://www.lichtenberg.fahrschulesafe.com",
]

# === Apps ===
INSTALLED_APPS = [
    'django.contrib.admin',         # Admin-Backend
    'django.contrib.auth',          # Auth-System
    'django.contrib.contenttypes',  # Content-Type-Framework
    'django.contrib.sessions',      # Sessions
    'django.contrib.messages',      # Messages/Flash
    'django.contrib.staticfiles',   # Staticfiles-Handling
    'core',                         # meine App
]


# === Middleware-Kette ===
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',            # Security/Headers
    'django.contrib.sessions.middleware.SessionMiddleware',     # Session-Handling
    'django.middleware.common.CommonMiddleware',                # Common goodies (z. B. ETags)
    'django.middleware.csrf.CsrfViewMiddleware',                # CSRF-Schutz
    'django.contrib.auth.middleware.AuthenticationMiddleware',  # User auf request
    'django.contrib.messages.middleware.MessageMiddleware',     # Messages in Templates
    'django.middleware.clickjacking.XFrameOptionsMiddleware',   # Clickjacking-Schutz
]


# === URL/WSGI ===
# Root-URLConf des Projekts
ROOT_URLCONF = 'fahrstundenplaner.urls'

# Template-Engine-Setup
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Eigener Template-Ordner (global). Zusätzlich zu App-Templates (APP_DIRS=True)
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,  # sucht auch in <app>/templates/
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',  # request in Templates
                'django.contrib.auth.context_processors.auth', # user/perm in Templates
                'django.contrib.messages.context_processors.messages', # messages
            ],
        },
    },
]

# Auth-Redirects (eigene Login-Flow-URLs)
LOGIN_URL = "/accounts/login/"                # wohin, wenn login verlangt wird
LOGIN_REDIRECT_URL = "post_login_redirect"    # nach Login je nach Rolle umleiten
LOGOUT_REDIRECT_URL = "login"                     # nach Logout zurück zur Startseite

# WSGI-Entry-Point (für Deployment mit Gunicorn/uwsgi etc.)
WSGI_APPLICATION = 'fahrstundenplaner.wsgi.application'


# === Datenbank ===
# Für Dev SQLite – easy. In Prod: auf Postgres/MySQL umstellen.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',  # SQLite für lokale Entwicklung
        'NAME': BASE_DIR / 'db.sqlite3',         # Datei im Projektverzeichnis
    }
}


# === Passwort-Validierung ===
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},   # Default min_length=8
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# === Session/Logout-Verhalten ===
# So bleibt der Login max. 8h gültig; Browser schließen loggt aus;
# bei Aktivität wird die Session verlängert (Sliding Session).
SESSION_COOKIE_AGE = 60 * 60 * 8         # 8 Stunden
SESSION_EXPIRE_AT_BROWSER_CLOSE = True   # beim Schließen ausloggen
SESSION_SAVE_EVERY_REQUEST = True        # Sliding Timeout aktiv


# === Internationalisierung / Zeitzone ===
LANGUAGE_CODE = 'de'            # UI/Texte auf Deutsch
TIME_ZONE = 'Europe/Berlin'     # Server-/Default-Zeitzone
USE_TZ = True                   # Zeitzonenbewusste Datetimes (empfohlen)

# === Static Files ===
# In Dev: Django dient staticfiles. In Prod: über Collectstatic + Webserver/Storage.
STATIC_URL = 'static/'          # URL-Prefix für statische Dateien
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Default PK-Typ für neue Modelle
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
